apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
spec:
  minReplicas: 3  # 최소 replicas 개수
  maxReplicas: 10  # 최대 replicas 개수
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 120
  metrics:
  - type: Resource  # 리소스 타입 선언
    resource:
      name: cpu  # HPA를 구성할 리소스(CPU, MEM 등)
      target:
        type: Utilization
        averageUtilization: 70  # CPU 사용률이 30% 이상일 경우 생성
  scaleTargetRef:  # 스케일 아웃할 타겟 설정
    apiVersion: apps/v1
    kind: Deployment  #  스케일 아웃할 타겟의 종류 (deployment, replicaset 등)
    name: frontend-server  #  스케일 아웃할 타겟의 네임
