apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: monitoring
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://10.0.20.14:3100/loki/api/v1/push

    scrape_configs:
    - job_name: system 
      static_configs:
      - targets:
          - localhost
        labels:
          job: varllll
          __path__: /var/log/*log   
      
      